DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    product VARCHAR NOT NULL,
    price VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
